version: 0.2

phases:
  pre_build:
    commands:
      - cd cicd # change directory
      # - chmod +x eks-install.sh setup-eks.sh configure-named-profile.sh # make files executable
      - echo install terraform 
      - bash install-terraform-ubuntu.sh # install terraform
      - bash configure-named-profile.sh # configure named profile
      - bash k8s-tools-install.sh

  build:
    commands:
      - echo build started on `date`
      - bash deploy-k8s.sh
      - echo build finished on `date`