version: 0.2

phases:
  pre_build:
    commands:
      - cd cicd # change directory
      - chmod +x eks-install.sh setup-eks.sh configure-named-profile.sh # make files executable
      - ./k8s-tools-install.sh # install terraform
      - ./configure-named-profile.sh # configure named profile

  build:
    commands:
      - echo build started on `date`
      - echo delete k8s
      - bash undeploy-k8s.sh
      - bash setup-eks.sh
      - echo deployment done at `date`