apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-api
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      component: fibonnaci
  template:
    metadata:
      labels:
        component: fibonnaci
    spec:
      containers:
        - name: fib-app
          image: 116429386222.dkr.ecr.us-east-1.amazonaws.com/fibonacci:1.0
          ports:
            - containerPort: 5000
          env:
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: '6379'