apiVersion: networking.k8s.io/v1
kind: Ingress 
metadata:
    name: ingress-service-eks
    annotations: 
      cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: nginx 
  rules:
  - host: "a561a5cbe5fec4df6a34007be45cd9b5-2b3d852c70d0e2c0.elb.us-east-1.amazonaws.com" # your purchased domain
    http:
      paths:
        - path: "/"
          pathType: Prefix
          backend:
            service:
              name: api-cluster-ip-service
              port: 
                  number: 5000
        - path: "/hello-world"
          pathType: Prefix
          backend:
            service:
              name: hello-world-service
              port: 
                  number: 8080
  tls:
  - hosts:
    - "a561a5cbe5fec4df6a34007be45cd9b5-2b3d852c70d0e2c0.elb.us-east-1.amazonaws.com"
    secretName: api-fibonacci-cert
    