name: Deploy Fibonnaci app to production

on:
  push:
    branches: [main]


env:
# environment controller
  TERRAFORM_ACTION: plan
  IMAGE_NAME: "fibonacci"
  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  aws-region: ${{ secrets.AWS_REGION }}


jobs:    
  # build AWS infrastructure for EKS cluster
  deploy_aws_infrastructure:
    name: build AWS infra
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Terraforn
        uses: hashicorp/setup-terraform@v2
        # with:
        #   terraform_version: v1.4.6
      
      - name: Initialize terraform  
        working-directory: ./iac/terraform-infrastructure
        run: terraform init

      - name: Run Terraform apply/destroy
        working-directory: ./iac/terraform-infrastructure
        run: terraform ${{ env.TERRAFORM_ACTION }} -lock=false
        continue-on-error: true


      
