name: Deploy Fibonnaci app to production

on:
  push:
    branches: [main]


env:
# environment controller
  TERRAFORM_ACTION: plan
  IMAGE_NAME: "fibonacci"
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:    
  # build AWS infrastructure for EKS cluster
  deploy_aws_infrastructure:
    name: build AWS infra
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Terraforn
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: v1.5.7
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Initialize terraform  
        working-directory: ./iac/terraform-infrastructure
        run: terraform init

      - name: Run Terraform apply/destroy
        working-directory: ./iac/terraform-infrastructure
        run: terraform plan 
        continue-on-error: true


      
